name: hello_world
description: "A new Flutter project."
publish_to: 'none' # Keeps the package private

environment:
  sdk: ">=3.5.1 <4.0.0" # Update to the latest Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Use the latest lint version

# Assets section
flutter:
  uses-material-design: true
  assets:
    - assets/logo_polinema.png

# Versioning
version: 1.0.0+1
